window.addEventListener('load', () => {
  const results = [];
  const root = document.documentElement;
  const value = (selector, property) => getComputedStyle(document.querySelector(selector))[property];
  const check = (name, actual, expected) => results.push(`${actual === expected ? 'PASS' : 'FAIL'} ${name}: ${actual}`);
  const rgb = color => color.match(/[\d.]+/g).slice(0, 3).map(Number);
  const luminance = color => rgb(color).map(channel => {
    const normalized = channel / 255;
    return normalized <= 0.04045 ? normalized / 12.92 : ((normalized + 0.055) / 1.055) ** 2.4;
  }).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const checkContrast = (name, textSelector, surfaceSelector) => {
    const text = luminance(value(textSelector, 'color'));
    const surface = luminance(value(surfaceSelector, 'backgroundColor'));
    const ratio = (Math.max(text, surface) + 0.05) / (Math.min(text, surface) + 0.05);
    results.push(`${ratio >= 4.5 ? 'PASS' : 'FAIL'} ${name}: ${ratio.toFixed(2)}:1 (minimum 4.5:1)`);
  };
  check('dark toolbar', value('.goog-toolbar-button', 'backgroundColor'), 'rgb(39, 39, 39)');
  check('selected toolbar', value('.goog-toolbar-button-checked', 'backgroundColor'), 'rgb(71, 71, 71)');
  check('menu text', value('.menu-button', 'color'), 'rgb(227, 227, 227)');
  check('menu surface', value('.goog-menu', 'backgroundColor'), 'rgb(48, 48, 48)');
  check('title shadow removed', value('.docs-title-input', 'textShadow'), 'none');
  check('title only paints once', value('.docs-title-input', 'color'), 'rgba(0, 0, 0, 0)');
  check('dark document paper', value('.kix-page', 'filter').startsWith('invert(1)'), true);
  check('comments header', value('.docs-docos-activity-sidebar-header', 'backgroundColor'), 'rgb(39, 39, 39)');
  check('comments empty state', value('.docos-streampane-zero-state', 'backgroundColor'), 'rgb(39, 39, 39)');
  check('comments empty-state text', value('.docos-streampane-zero-state-content-add-comment', 'color'), 'rgb(227, 227, 227)');
  check('comments selected tab', value('.docs-tabbar-tab-selected', 'backgroundColor'), 'rgb(59, 59, 59)');
  check('document selected tab', value('.chapter-item-label-and-buttons-container-selected', 'backgroundColor'), 'rgb(71, 71, 71)');
  check('primary action', value('.docs-material-button-fill-primary', 'backgroundColor'), 'rgb(222, 222, 222)');
  check('primary action text', value('.docs-material-button-fill-primary', 'color'), 'rgb(36, 36, 36)');
  check('tooltip surface is dark', luminance(value('#toolbar-tooltip', 'backgroundColor')) < 0.1, true);
  check('chat tooltip surface is dark', luminance(value('.docs-chat-message-tooltip-container', 'backgroundColor')) < 0.1, true);
  checkContrast('toolbar tooltip contrast', '#toolbar-tooltip', '#toolbar-tooltip');
  checkContrast('share tooltip title contrast', '.scb-tooltip-title', '#share-tooltip');
  checkContrast('share tooltip description contrast', '.scb-tooltip-text', '#share-tooltip');
  checkContrast('chat tooltip contrast', '.docs-chat-message-tooltip-content', '.docs-chat-message-tooltip-container');
  checkContrast('link preview title contrast', '.docs-link-bubble-text-card-component span', '.docs-linkbubble-bubble');
  checkContrast('popover link contrast', '.docs-bubble-link', '.docs-linkbubble-bubble');
  root.dataset.darkDocsPaper = 'original';
  check('original paper unfiltered', value('.kix-page', 'filter'), 'none');
  root.dataset.darkDocsPaper = 'dark';
  root.dataset.darkDocs = 'light';
  check('light mode restores original UI', value('.goog-toolbar-button', 'backgroundColor'), 'rgb(240, 244, 249)');
  check('light mode restores paper', value('.kix-page', 'filter'), 'none');
  check('light mode restores tooltip surface', value('#toolbar-tooltip', 'backgroundColor'), 'rgb(255, 255, 255)');
  check('light mode restores tooltip text', value('.scb-tooltip-title', 'color'), 'rgb(32, 33, 36)');
  root.dataset.darkDocs = 'dark';
  document.querySelector('#results').textContent = results.join('\n');
});
